### ISSUE TITLE
Android上的chrome推送不成功

### ISSUE THREAD

**Issue by lvming6816077** [alienzhou/learning-pwa#6]
在PC上使用推送，用了proxy，可以看到推送消息，当时当用Android上的chrome访问时，就收不到推送，在用
```javascript
const subscription = registration.pushManager.subscribe({
                  userVisibleOnly: true,
                  applicationServerKey: urlBase64ToUint8Array(publicKey)
                })
```
时报错，aborterror: registration failed - push service error

请问有遇到过吗

**Comment by alienzhou** [comment]
可能是无法访问推送服务，Android 机上是否有开启代理呢？

**Comment by oneheartyang** [comment]
同问, PC 上使用 firefox 可以看到推送消息, 手机上使用 firefox 就报错, 而且错误提示只显示 "DOMException",

请问有遇到过么, 如果要开代理, 是要单独部一个代理服务么?

**Comment by lvming6816077** [comment]
Android上想要使用推送需要翻墙
