### ISSUE TITLE
如何存储客户端信息呢？ 还有如何一次性向所有客户端推送消息

### ISSUE THREAD

**Issue by 5dong** [alienzhou/learning-pwa#7]
还有这种服务部署的话怎么操作 就是想实现消息推送 可能服务端是单独部署 如何存储客户端信息呢？
非常感谢！

**Comment by alienzhou** [comment]
消息的推送需要通过 Push Service，客户端在调用订阅消息的 API 后会得到 PushSubscription 对象，其中包含了推送地址与一些 key，客户端将它发送到服务端，然后由服务端存储（例如存到数据库里）；
需要推送时可以从数据库中读出来，根据 PushSubscription 的信息与 Push Service 通信，Push Service 会将消息推送到客户端。
